app:
    resource: "@AppBundle/Controller/"
    type:     annotation

awsomecms_fallback:
    path: /{path}
    defaults: { _controller: "awsomecms.controller.fallback:fallback" }
    requirements:
      path: .*

awesomecms_routes:
    resource: "@AwsomecmsBundle/Resources/config/routing.yml" 