app:
    resource: "@AppBundle/Controller/"
    type:     annotation

awsomecms:
    path: /{path}
    defaults: { _controller: "awsomecms.controller.fallback:fallback" }
    requirements:
      path: .*