services:
    awsomecms.controller.fallback:
        class: Bundle\AwsomecmsBundle\Controller\FallbackController
        arguments:
            - "@service_container"
            - "%awsomecms.website_root%"
